# Generated by Django 2.2.5 on 2019-10-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(blank=True, max_length=70, unique=True)),
                ('active', models.BooleanField(blank=True)),
                ('amount', models.BigIntegerField(blank=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('product', models.CharField(blank=True, max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(blank=True, max_length=10)),
                ('plan_id', models.CharField(blank=True, max_length=70)),
                ('account', models.ForeignKey(on_delete=None, to='account.Account')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
