# Generated by Django 2.2.5 on 2019-10-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20191002_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name_plural': 'Plans'},
        ),
    ]
