image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - deploy

image-build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/zburau/wanderift-django .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/zburau/wanderift-django

k8s-deploy:
  image: google/cloud-sdk
  stage: deploy
  script:
    - kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user ${CI_REGISTRY_USER}
    - kubectl config set-cluster model-gen --server=$KUBE_URL --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --token=$KUBE_TOKEN
    - kubectl config set-context default-context --cluster=model-gen --user=admin
    - kubectl config use-context default-context
    - kubectl create -f rbac.yml
    - helm init --service-account tiller
    - kubectl create namespace kube-system
    - kubectl delete secret gitlab-registry --ignore-not-found
    - kubectl create secret docker-registry gitlab-registry --docker-server=${CI_REGISTRY} --docker-username=${CI_REGISTRY_USER} --docker-password=${CI_REGISTRY_PASSWORD} --docker-email=${CI_REGISTRY_EMAIL}
    - kubectl apply -f deployment.yml
    - kubectl apply -f ingress.yml
    - kubectl apply -f service.yml
    - kubectl apply -f certificate.yml
  environment:
    name: prod
  when: on_success

