apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wanderift-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: false
    networking.gke.io/managed-certificates: wanderift-certificate
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
    - host: www.wanderift.com
      http:
        paths:
          - path: /
            backend:
              serviceName: wanderift-service
              servicePort: 80

