apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wanderift-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: false
  rules:
    - host: www.wanderift.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: wanderift-service
              servicePort: 80

