apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wanderift-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: wanderift
          servicePort: 80
