apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wanderift-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - wanderift.com
      secretName: wanderift-cert-secret
  rules:
    - host: wanderift.com
      http:
        paths:
          - path: /
            backend:
              serviceName: wanderift-service
              servicePort: 80

