apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wanderift-app
rules:
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
      - endpoints
      - pods
      - configmaps
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
      - patch
  - update
  - apiGroups:
      - ""
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete

---

apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: wanderift-app

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wanderift-app
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wanderift-app
subjects:
  - kind: ServiceAccount
    name: wanderift-app
    namespace: default
