apiVersion: v1
kind: Service
metadata:
  name: wanderift
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
  selector:
    app: wanderift
  type: LoadBalancer
  readinessProbe:
    httpGet:
      path: /healthz
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 5
