apiVersion: v1
kind: Service
metadata:
  name: wanderift-service
spec:
  ports:
    - port: 81
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: wanderift-service
  type: LoadBalancer
