# Generated by Django 2.2.5 on 2019-10-13 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('plan', models.CharField(max_length=30)),
                ('tokens', models.IntegerField(default=0)),
                ('rollover', models.IntegerField(default=0)),
                ('price', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionsSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Subscription Summary',
                'verbose_name_plural': 'Subscriptions Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subscriptions.subscriptions',),
        ),
    ]
