# Generated by Django 2.2.5 on 2019-11-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='rollover',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='tokens',
        ),
    ]
