# Generated by Django 2.2.5 on 2019-11-26 19:47

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20191107_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='period',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
        ),
    ]
