# Generated by Django 2.2.5 on 2019-11-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20191013_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='account',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
