# Generated by Django 2.2.8 on 2019-12-08 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentflyer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oauth.User'),
        ),
        migrations.AddField(
            model_name='dealwatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.User'),
        ),
    ]
