# Generated by Django 2.2.5 on 2019-10-20 13:33

import apps.account.enums
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [("account", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="profile", name="gender"),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=django_enumfield.db.fields.EnumField(
                default=0, enum=apps.account.enums.Gender
            ),
        ),
    ]
