# Generated by Django 2.2.5 on 2019-10-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_gender_field_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tsa_precheck_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
