# Generated by Django 2.2.5 on 2019-11-06 01:29

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191105_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=creditcards.models.CardNumberField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='cvc',
            field=creditcards.models.SecurityCodeField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='expiry',
            field=creditcards.models.CardExpiryField(null=True),
        ),
    ]
