# Generated by Django 2.2.7 on 2019-11-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191106_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='secret',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
