# Generated by Django 2.2.5 on 2019-11-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20191119_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='market',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
