# Generated by Django 2.2.5 on 2019-11-22 01:46
import json

from django.db import migrations

def remove_bad_json_fields(apps, schema_editor):
    Profile = apps.get_model("account", "Profile")
    for o in Profile.objects.all():
        try:
            json.loads(o.market)
        except ValueError:
            o.market = None
            o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20191122_0146'),
    ]

    operations = [
        migrations.RunPython(remove_bad_json_fields, migrations.RunPython.noop)
    ]
