# Generated by Django 2.2.5 on 2019-11-22 01:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191122_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='market',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
