# Generated by Django 2.2.5 on 2019-11-27 21:43

import apps.account.enums
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20191122_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=django_enumfield.db.fields.EnumField(blank=True, default=0, enum=apps.account.enums.Gender, null=True),
        ),
    ]
