# Generated by Django 2.2.8 on 2019-12-03 15:57

import apps.account.enums
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20191127_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=apps.account.enums.Gender, null=True),
        ),
    ]
