# Generated by Django 2.2.8 on 2019-12-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20191203_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealWatch',
        ),
    ]
