# Generated by Django 2.2.8 on 2019-12-04 22:21

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0014_delete_dealwatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', django.contrib.postgres.fields.jsonb.JSONField()),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('airlines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
