# Generated by Django 2.2.5 on 2019-10-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptions_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionsSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Subscription Summary',
                'verbose_name_plural': 'Subscriptions Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subscriptions.subscriptions',),
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name_plural': 'Subscriptions'},
        ),
    ]
