# Generated by Django 2.2.5 on 2019-11-26 01:41

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_from', models.CharField(max_length=50)),
                ('city_to', models.CharField(max_length=50)),
                ('city_from_name', models.CharField(max_length=50)),
                ('city_to_name', models.CharField(max_length=50)),
                ('fly_from', models.CharField(max_length=50)),
                ('fly_to', models.CharField(max_length=50)),
                ('dt_departure', models.DateTimeField()),
                ('dt_return', models.DateTimeField()),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('return_date', models.DateField()),
                ('return_time', models.TimeField()),
                ('airlines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_id', models.TextField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['city_from', 'city_to'], name='booking_dea_city_fr_9f9bdb_btree'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['fly_from', 'fly_to'], name='booking_dea_fly_fro_aaafa6_btree'),
        ),
    ]
