# Generated by Django 2.2.5 on 2019-11-26 21:06
import json
import django.contrib.postgres.fields.jsonb
from django.db import migrations


def remove_bad_json_fields(apps, schema_editor):
    Flight = apps.get_model("booking", "Flight")
    BookingContact = apps.get_model("booking", "BookingContact")
    for model in (Flight, BookingContact):
        for o in model.objects.all():
            try:
                json.loads(o.data)
            except ValueError:
                o.data = None
                o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20191126_0141'),
    ]

    operations = [
        migrations.RunPython(remove_bad_json_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bookingcontact',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
