# Generated by Django 2.2.5 on 2019-12-03 00:24

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_auto_20191126_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('place_from', django.contrib.postgres.fields.jsonb.JSONField()),
                ('place_to', django.contrib.postgres.fields.jsonb.JSONField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('adults', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
                ('infants', models.IntegerField(default=0)),
                ('seat_type', models.CharField(max_length=10)),
                ('destination_type', models.CharField(choices=[('round', 'Round Trip'), ('oneway', 'Oneway')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['timestamp'], name='booking_sea_timesta_0bf27c_btree'),
        ),
    ]
