apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderift-deployment
spec:
  selector:
    matchLabels:
      app: wanderift
  replicas: 1
  template:
    metadata:
      labels:
        app: wanderift
    spec:
      volumes:
        - name: gce-service-account-key
          secret:
            secretName: gce-service-account-key
      containers:
        - name: wanderift
          image: registry.gitlab.com/zburau/wanderift-django
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: POSTGRES_PASSWORD

            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: STRIPE_API_KEY

            - name: STRIPE_BASIC_PLAN_ID
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: STRIPE_BASIC_PLAN_ID

            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'

          volumeMounts:
            - name: gce-service-account-key
              readOnly: true
              mountPath: /etc/secrets
        - name: worker
          command: ['inv', 'worker']
          image: registry.gitlab.com/zburau/wanderift-django
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: POSTGRES_PASSWORD

            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: STRIPE_API_KEY

            - name: MAINTENANCE_MODE
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: MAINTENANCE_MODE

            - name: STRIPE_BASIC_PLAN_ID
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: STRIPE_BASIC_PLAN_ID

            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'

          volumeMounts:
            - name: gce-service-account-key
              readOnly: true
              mountPath: /etc/secrets
      initContainers:
        - name: migrate
          image: registry.gitlab.com/zburau/wanderift-django
          command: ['python', 'manage.py', 'migrate']
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: POSTGRES_PASSWORD

            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: STRIPE_API_KEY

            - name: STRIPE_BASIC_PLAN_ID
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: STRIPE_BASIC_PLAN_ID

            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          volumeMounts:
            - name: gce-service-account-key
              readOnly: true
              mountPath: /etc/secrets
        - name: collectstatic
          image: registry.gitlab.com/zburau/wanderift-django
          command: ['python', 'manage.py', 'collectstatic', '--noinput',  '-v', '3']
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: POSTGRES_PASSWORD

            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: STRIPE_API_KEY

            - name: STRIPE_BASIC_PLAN_ID
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: STRIPE_BASIC_PLAN_ID

            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          volumeMounts:
            - name: gce-service-account-key
              readOnly: true
              mountPath: /etc/secrets
      imagePullSecrets:
        - name: gitlab-registry
